# SYNTAX for arange function in numpy.
np.arange(start, end, step) 

UNDER THE HOOD:

np.arange([start,] stop[, step], dtype=None)

start and step are optional

In [2]:
import numpy as np

## How do I store values from 0 to 9 in a 1D array?

In [10]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


## How do I store values from 1 to 10?

In [9]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


## How do I create an array of even numbers from 0 to 10?

In [11]:
a = np.arange(0,11,2)
print(a)

[ 0  2  4  6  8 10]


## How do I create an array of odd numbers from 1 to 9?

In [12]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


## How do I store multiples of 3 from 3 to 30?

In [13]:
a = np.arange(3,31,3)
print(a)

[ 3  6  9 12 15 18 21 24 27 30]


## How do I create a descending array from 10 to 1?

In [14]:
a = np.arange(10, 0, -1)
print(a)

[10  9  8  7  6  5  4  3  2  1]


## How do I create an array from 100 to 10 in steps of -10?

In [17]:
a = np.arange(100,9,-10)
print(a)

[100  90  80  70  60  50  40  30  20  10]


## How do I create values from 0 to 1 with step size 0.2?

In [19]:
a = np.arange(0,1.1,0.2)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


## How do I create decimal values from 5.5 to 10 with a step of 0.5?

In [20]:
a = np.arange(5.5, 10.1, 0.5)
print(a)

[ 5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10. ]


## How do I create an array of float numbers from 1 to 5?

In [21]:
a = np.arange(1,6, dtype = float)
print(a)

[1. 2. 3. 4. 5.]


# SYNTAX for reshape and flatten function.

## How do I convert a 1D array of 6 elements into a 2×3 matrix?

In [24]:
a = np.array([1,2,3,4,5,6])
a = a.reshape(2, 3)
print (a)

[[1 2 3]
 [4 5 6]]


 ## How do I reshape a 3×3 matrix into a 1D array?

In [32]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = a.flatten()
print (b)

[1 2 3 4 5 6 7 8 9]


 ## How do I reshape a 3×3 matrix into a 1D array by reference?


In [30]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = a.ravel()
print(b)

[1 2 3 4 5 6 7 8 9]
