In [1]:
import numpy as np

### Python list store only one dimentional array

In [2]:
lst = [1,2,3,4]
print(lst)

[1, 2, 3, 4]


### Numpy array can have multiple dimension (1D, 2D, 3D)

In [10]:
print('1D Array')
a = np.array([1,2,3,4])
print(a)

1D Array
[1 2 3 4]


In [13]:
print('2D Array: array of arrays')
b = np.array([[1,2,3,4],
             [5,6,7,8]])
print(b)

2D Array: array of arrays
[[1 2 3 4]
 [5 6 7 8]]


In [12]:
print('3D Array:', 'array of array of arrays')
c = np.array([[[1,2,3,4],[5,6,7,8]],
             [[9,10,11,12],[13,14,15,16]]])
print(c)

3D Array: array of array of arrays
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


### How find the type of variable: a, b, c ?

In [14]:
type(a)

numpy.ndarray

In [15]:
type(b)

numpy.ndarray

In [16]:
type(c)

numpy.ndarray

This means a, b, c are numpy arrays of ndarray class meaning N dimensional array. 

### How find the structure (shape) of numpy array?

In [18]:
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 4)
(2, 2, 4)


a is an array containing 4 elements

b is an array containing 2 arrays, each of them containing 4 elements

c is an array containing 2 arrays, each of them containing 2 arrays, each of them containing 4 elements.

c means two layers of (2,4) matrix.


### How find total number of elements in numpy array?

In [17]:
print(a.size)
print(b.size)
print(c.size)

4
8
16


### How find the type of data present numpy array?

In [19]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


### How to transpose i.e. interchange rows and columns of matrix formed by 2D array?

In [24]:
print('2D Array')
d = np.array([[1,2,3,4],
             [5,6,7,8]])
print(d)

print()
print('Transpose')
print (d.transpose())

2D Array
[[1 2 3 4]
 [5 6 7 8]]

Transpose
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
