### Syntax for empty, ones and zeros numpy functions
np.function((rows,columns), dtype = datatype)

### How do I create a NumPy array with a given shape and type without initializing its values?

In [28]:
import numpy as np

In [29]:
a = np.empty((3,4), dtype = int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### Why call it empty function when it is giving array with zero integer or sometimes even random integer?
because we care about performance and we just want an array with this shape and data type while not caring about values inside it - just make it fast. Later, we are going to overwrite the values anyway.

### How do I create a NumPy array with a given shape and type and initializing each values with one?

In [30]:
c = np.ones((3,4), dtype = int)
print (c)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


### How do I create a NumPy array with a given shape and type and initializing each values with zero?

In [31]:
d = np.zeros((3,4), dtype = int)
print(d)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### In syntax, what happens when we don't specify the data type in zeros and ones function?
float becomes default data type

In [32]:
e = np.zeros((3,4))
print(e)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### In syntax, what happens when we don't specify the data type as well as columns in zeros and ones function?
float becomes default data type and it will create one dimensional simple array.

In [33]:
f = np.zeros(3)
print(f)

[0. 0. 0.]


### How do I create a NumPy array of of certain dimension containing empty strings and '1' strings?
by using str data type in np.zeros function and np.ones functions respectively. 

In [34]:
g = np.zeros((3,4), dtype = str)
print(g)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [35]:
h = np.ones((3,4), dtype = str)
print(h)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


### How do I create a NumPy array of a certain dimension containing False and True boolean values?
By using the bool data type in np.zeros() and np.ones() functions respectively.

In [36]:
i = np.zeros((3,4), dtype = bool)
print(i)

[[False False False False]
 [False False False False]
 [False False False False]]


In [37]:
j = np.ones((3,4), dtype = bool)
print(j)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
